services:

  goose:
    image: artsafin/goose-migrations
    hostname: goose
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: "postgres postgres://postgres:postgres@postgres:5432/bank_db?sslmode=disable up"
