name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: verify
        run: make verify

      - name: test
        run: make test